apiVersion: v1
kind: ConfigMap
metadata:
  name: sureguard-config
  namespace: sureguard
data:
  NODE_ENV: "production"
  CORS_ORIGIN: "https://sureguard.ai"
  RATE_LIMIT_WINDOW_MS: "900000"
  RATE_LIMIT_MAX: "1000"
  JWT_EXPIRES_IN: "15m"
  JWT_REFRESH_EXPIRES_IN: "7d"
  ML_MODEL_UPDATE_FREQUENCY: "24h"
  THREAT_RETENTION_DAYS: "90"
  API_TIMEOUT_MS: "30000"
  BATCH_SIZE_LIMIT: "100"
  CACHE_TTL_SECONDS: "300"
  LOG_LEVEL: "info"
